// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachePaths } from "./CachePaths";
import type { LibrarySource } from "./LibrarySource";
import type { SongSort } from "./SongSort";

export type AppConfig = { data_path: string | null, cache_paths: CachePaths | null, 
/**
 * Deprecated. Kept for one-shot migration into `library_source`; never
 * written by code that has been through `with_defaults`.
 */
last_folder: string | null, library_source: LibrarySource | null, last_theme: number | null, guide_volume: number | null, fullscreen: boolean | null, playback_mode: string | null, dark_mode: boolean | null, mic_active: boolean | null, 
/**
 * `serde(alias = "mic_mirroring")` keeps configs written by builds that
 * called this feature "mic mirroring" loading without a manual migration;
 * the next `save` rewrites them under the new name.
 */
mic_monitoring: boolean | null, mic_monitor_gain: number | null, mic_latency_compensation_sec: number | null, preferred_mic: string | null, whisper_model: string | null, beam_size: number | null, batch_size: number | null, last_video_flavor: number | null, lyrics_vertical_position: string | null, lyrics_horizontal_position: string | null, lyrics_scale: number | null, pitch_graph_scale: number | null, separator: string | null, asr_engine: string | null, align_backend: string | null, vocal_detection_threshold_pct: number | null, auto_analyze: boolean | null, 
/**
 * When set, analysis always runs WhisperX to produce word-level lyric
 * timing. Default (`None`/false) uses LRCLIB's line-level synced lyrics and
 * skips WhisperX entirely — songs with no synced match are left lyric-less
 * (stems only) rather than transcribed. See docs/adr/0003.
 */
word_level_lyrics: boolean | null, 
/**
 * When set, analysis looks the song up on LRCLIB and uses any synced
 * lyrics it finds. Default (`None`/false) skips the lookup entirely and
 * only separates stems — see docs/adr/0003.
 */
lyrics_lookup: boolean | null, 
/**
 * How many songs are analyzed at once (1-2). Each worker runs its own
 * analyzer server process, so 2 doubles GPU/RAM use. Default 2.
 */
analysis_workers: number | null, 
/**
 * Pitch-scoring tolerance in semitones — the distance at which a sung note
 * scores zero (`similarity = max(0, 1 - diff/tolerance)`). Lower is
 * stricter, higher is more forgiving. Default 6.
 */
pitch_tolerance_semitones: number | null, 
/**
 * When set, finishing a song starts a random analyzed song from the
 * library instead of returning to the menu. Default (`None`/false) keeps
 * the exit-to-menu behaviour.
 */
auto_play_next: boolean | null, 
/**
 * Opt-in for the LAN remote-control listener. Defaults to false, and the
 * listener still only starts when the UI asks for it.
 */
remote_control: boolean, 
/**
 * Opt-in for letting a phone on the remote page submit a YouTube link to
 * import. Off by default: the party surface is unauthenticated, and this
 * is the one thing on it that runs a subprocess and writes to the library
 * folder. Anyone who can reach the address can use it.
 */
party_import: boolean, 
/**
 * Opt-in for letting a phone on the remote page shift the playing song's
 * lyric timing. Off by default: the party surface is unauthenticated, and
 * a shift changes what everyone in the room reads. The shift is a display
 * offset on the running song only; nothing on disk changes.
 */
party_lyric_shift: boolean, song_list_view: string | null, song_list_sort: Array<SongSort> | null, language_overrides: { [key in string]: string } | null, };
