// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheStats = { songs_bytes: bigint, videos_bytes: bigint, models_bytes: bigint, other_bytes: bigint, clearable_videos_bytes: bigint, };
