// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CachePaths = { songs: string | null, videos: string | null, models: string | null, vendor: string | null, };
