// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who asked for an import. A phone's submission is acted on more freely than
 * a desktop one — it has no screen to come back to — so the origin has to
 * survive in the queue rather than being decided at the call site.
 */
export type ImportSubmitter = "Desktop" | "Phone";
