// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportEntry } from "./ImportEntry";

export type ImportPreview = {
  isPlaylist: boolean;
  /**
   * Stable playlist id (yt-dlp `id`), used to recognise a re-import of the
   * same playlist and reuse its `.m3u`. `None` for a single video.
   */
  playlistId: string | null;
  /**
   * Playlist title, when the URL resolved to a playlist.
   */
  playlistTitle: string | null;
  entries: Array<ImportEntry>;
};
