// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one entry has got to. Terminal for everything from `Imported` down.
 */
export type ImportEntryStatus = "Draft" | "Queued" | "Downloading" | "Imported" | "Skipped" | "Failed";
