// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a row came from. Recorded rather than acted on: an import does the
 * same thing whoever asked for it, and the queue is shared, so this is what
 * lets a row be read back as somebody's rather than nobody's.
 */
export type ImportSubmitter = "Desktop" | "Phone";
