// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportEntry = {
  /**
   * YouTube video id — the stable handle we re-download by.
   */
  id: string;
  title: string;
  artist: string;
  durationSecs: number;
};
