// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportEntryProgress } from "./ImportEntryProgress";

/**
 * Progress tick emitted while a (possibly background) import runs.
 */
export type ImportProgress = {
  done: number;
  total: number;
  /**
   * Title of the entry currently being downloaded, if any.
   */
  current: string | null;
  /**
   * Download fraction (0.0–1.0) of the current entry.
   */
  currentPct: number;
  imported: number;
  skipped: number;
  failed: number;
  /**
   * The single entry this tick is about, so a listener can accumulate
   * per-entry state without the aggregate carrying the whole list every
   * tick. `None` on the closing summary tick.
   */
  entry: ImportEntryProgress | null;
};
