// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportEntryStatus } from "./ImportEntryStatus";

/**
 * One entry's state at a point in time. Several entries download at once
 * (`DOWNLOAD_CONCURRENCY`), so a listener keyed by `id` can show each of them
 * moving independently — which the aggregate counters below cannot express.
 */
export type ImportEntryProgress = {
  /**
   * YouTube video id — the stable key a listener addresses rows by.
   */
  id: string;
  status: ImportEntryStatus;
  /**
   * Download fraction (0.0–1.0). 1.0 for every terminal status.
   */
  pct: number;
  /**
   * Failure text, present only on `Failed`.
   */
  reason: string | null;
};
