// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress tick emitted while a (possibly background) import runs.
 */
export type ImportProgress = {
  done: number;
  total: number;
  /**
   * Title of the entry currently being downloaded, if any.
   */
  current: string | null;
  imported: number;
  skipped: number;
  failed: number;
};
