// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFailure } from "./ImportFailure";

export type ImportReport = {
  imported: number;
  /**
   * Entries already present from a previous import (id matched, file on disk).
   */
  skipped: number;
  failed: Array<ImportFailure>;
  playlistName: string | null;
};
