// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogTail = { 
/**
 * Where the file is, so a reader can open it outside the app.
 */
path: string, text: string, 
/**
 * True when the file was longer than the tail that was read.
 */
truncated: boolean, };
