// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the renderer needs to talk to the local media server. The session
 * token is unguessable per-process so a webpage / co-tenant process cannot
 * fish files off the local-file route by enumerating localhost ports.
 */
export type MediaEndpoint = { port: number; session_token: string };
