// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public ping payload surfaced to the UI. Renders the small "online / offline"
 * pill next to the Navidrome source in the sidebar.
 */
export type NavidromeHealth = {
  reachable: boolean;
  server_name?: string;
  version?: string;
  error?: string;
};
