// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public auth response surfaced to the UI after a successful login.
 */
export type NavidromeLoginResult = {
  server_url: string;
  server_name: string | null;
  server_version: string | null;
  username: string;
  password: string;
};
