// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlexSection } from "./PlexSection";

export type PlexServer = {
  server_url: string;
  server_name: string;
  server_id: string;
  username: string;
  access_token: string;
  client_id: string;
  sections: Array<PlexSection>;
  owned: boolean;
};
