// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlexPinStart = {
  pin_id: string;
  code: string;
  client_id: string;
  auth_url: string;
  expires_in: number;
};
