// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlexServer } from "./PlexServer";

export type PlexPinPollResult = { authorized: boolean; servers: Array<PlexServer> };
