// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlexHealth = {
  reachable: boolean;
  server_name?: string;
  version?: string;
  server_id?: string;
  error?: string;
};
