// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreRecord } from "./ScoreRecord";

export type ProfileStore = { active: string | null, profiles: Array<string>, scores: Array<ScoreRecord>, };
