// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteStatus = { running: boolean, port: number | null, 
/**
 * What the QR code encodes for a phone on the same network.
 */
lan_url: string | null, 
/**
 * Where this webview connects as the host — over loopback, because the
 * host page and the listener are the same process.
 */
ws_url: string | null, };
