// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteProbe } from "./RemoteProbe";
import type { RemoteStatus } from "./RemoteStatus";

/**
 * What the desktop can establish about remote control without leaving the
 * machine: whether the listener is up, what address the QR code hands out,
 * and whether that address actually answers from here.
 *
 * A LAN address that fails here is the address itself — a lease that moved,
 * or an interface that is no longer the route out. A LAN address that
 * answers here but not from a phone is the network between them: a firewall,
 * client isolation on the access point, or a different subnet.
 */
export type RemoteDiagnostics = { status: RemoteStatus, loopback: RemoteProbe, lan: RemoteProbe, };
