// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One address the host tried to reach its own listener on.
 */
export type RemoteProbe = { 
/**
 * `null` when there was no address to try.
 */
address: string | null, ok: boolean, 
/**
 * The answer's status line, or why the attempt failed.
 */
detail: string, };
