// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScoreRecord = { profile: string; song_hash: string; score: number; played_at: bigint };
