// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupStep } from "./SetupStep";

export type SetupProgress = { step: SetupStep, percent: number, action: string, };
