// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachePaths } from "./CachePaths";

export type SetupFolders = { dataPath: string | null; cachePaths: CachePaths | null };
