// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShiftDone = {
  file_hash: string;
  key: string | null;
  tempo: number | null;
  error: string | null;
};
