// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the bytes for a song actually live. `LocalFile` means `Song.path` is the
 * real source-of-truth on disk; the remote variants (`Jellyfin`, `Navidrome`,
 * `Plex`) mean `Song.path` is a placeholder inside `cache/sources/` that the source
 * adapter will materialise on demand.
 *
 * The server's base URL deliberately does NOT live on the origin: it lives on
 * the active `AppConfig.library_source` and would otherwise go stale the next
 * time the user reconnects to a different host.
 */
export type SongOrigin =
  | { kind: "local_file" }
  | {
      kind: "jellyfin";
      item_id: string;
      container: string | null;
      /**
       * Jellyfin's `ImageTags.Primary` for this item, captured at scan
       * time. We re-fetch the cover only when this value changes.
       */
      cover_tag: string | null;
    }
  | {
      kind: "navidrome";
      item_id: string;
      container: string | null;
      /**
       * Subsonic `coverArt` id for this song, captured at scan time. We
       * re-fetch the cover only when this value changes.
       */
      cover_tag: string | null;
    }
  | {
      kind: "plex";
      item_id: string;
      /**
       * Server-relative original-media part key. Keeping it relative lets
       * the backend authenticate without exposing a token-bearing URL.
       */
      part_key: string;
      container: string | null;
      /**
       * Server-relative Plex thumb path used for cover invalidation.
       */
      cover_tag: string | null;
    };
