// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SongsMeta = {
  count: number;
  folder: string;
  processed_count: number;
  songs_count: number;
  videos_count: number;
  analyzed_count: number;
};
