// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sibling-file paths referenced by a USDX song, resolved relative to the .txt file's
 * parent directory. Stored on the Song row and consulted by playback to bypass the
 * stem-cache lookup entirely.
 */
export type UsdxBundle = {
  txt_path: string;
  audio: string;
  vocals: string | null;
  instrumental: string | null;
  video: string | null;
};
